services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: medlink
        container_name: medlink_app
        restart: unless-stopped
        ports:
            - "10002:80"
        volumes:
            - .:/var/www/html
            # - /var/www/html/vendor
            - /var/www/html/storage
