services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: medlink
        container_name: medlink_app
        restart: unless-stopped
        ports:
            - "10002:80"
        volumes:
            - .:/var/www/html
            - ./storage/logs:/var/www/html/storage/logs
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://localhost/api/health"]
        #     interval: 30s
        #     timeout: 10s
        #     retries: 3
        #     start_period: 40s
